---
abstract: 'Customisable queue list portlet for the RT homepage'
author:
  - 'misy <git@mymistake.de>'
distribution_type: module
generated_by: 'Module::Install'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RT-Extension-QueueListCustom
no_index:
  directory:
    - inc
    - t
perl_version: '5.010'
requires:
  RT: '6.0.0'
version: '1.0'
x_RT_too_new: '6.2.0'
